FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go run cmd/main.go

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main_app cmd/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main_app .

ENTRYPOINT ["./main_app"]
