FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o http_app cmd/http/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/http_app .

EXPOSE 8080

ENTRYPOINT ["./http_app"]
